//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Centrala
{
	private int Current_ID
	{
		get;
		set;
	}

	public virtual Abstrakcyjna_Jednostka straznik_listy_jednostek
	{
		get;
		set;
	}

	public virtual List<Abstrakcyjna_Fabryka_Rozkazow> Lista_Fabryk_Rozkazow
	{
		get;
		set;
	}

	public virtual void Dodaj(string nazwa_obiektu)
	{
		throw new System.NotImplementedException();
	}

	public Centrala()
	{
        Current_ID = 0;
        Lista_Fabryk_Rozkazow = new List<Abstrakcyjna_Fabryka_Rozkazow>();
        Lista_Fabryk_Rozkazow.Add(new FR_Cwiczenia());
        Lista_Fabryk_Rozkazow.Add(new FR_Mobilizacja());
        Lista_Fabryk_Rozkazow.Add(new FR_Produkuj());
        Lista_Fabryk_Rozkazow.Add(new FR_DodajZasobWojskowy());


    }

    public virtual void Odczytaj_Raport(string Raport)
    {
        Console.WriteLine(Raport);
    }

    public virtual void WydajRozkaz(string Tekst_Rozkazu)
	{
        string[] ParametryRozkazu = Tekst_Rozkazu.Split('|');
        Abstrakcyjny_Rozkaz Rozkaz = null;

        foreach (Abstrakcyjna_Fabryka_Rozkazow Fabryka in Lista_Fabryk_Rozkazow)
        {
            if (Fabryka.nazwa_rozkazu == ParametryRozkazu[0])
            {
                Rozkaz = Fabryka.TworzRozkaz(Tekst_Rozkazu, this);
                break;
            }
        }

        if (Rozkaz != null)
        {
            straznik_listy_jednostek.Wykonaj(Rozkaz);
        }
        else
        {
            Console.WriteLine("Bledna nazwa rozkazu");
        }
    }

    public virtual string Lista_Dostepnych_Rozkazow()
    {
        string ListaDostepnychRozkazow = "";
        foreach(Abstrakcyjna_Fabryka_Rozkazow Fabryka in Lista_Fabryk_Rozkazow)
        {
            ListaDostepnychRozkazow = ListaDostepnychRozkazow + " " + Fabryka.nazwa_rozkazu;
        }
        return ListaDostepnychRozkazow;
    }

    

}

