//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Centrala
{
	private int Current_ID
	{
		get;
		set;
	}

	public virtual Abstrakcyjna_Jednostka straznik_listy_jednostek
	{
		get;
		set;
	}

	public virtual Abstrakcyjna_Fabryka_Rozkazow Lista_Fabryk_Rozkazow
	{
		get;
		set;
	}

	public virtual void Dodaj(string nazwa_obiektu)
	{
		throw new System.NotImplementedException();
	}

	public Centrala()
	{
	}

	public virtual void WydajRozkaz(string Tekst_Rozkazu)
	{
		throw new System.NotImplementedException();
	}

	public virtual string Lista_Dostepnych_Rozkazow()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Odczytaj_Raport(string Raport)
	{
		throw new System.NotImplementedException();
	}

}

