//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FR_Mobilizacja : Abstrakcyjna_Fabryka_Rozkazow
{
	public override Abstrakcyjny_Rozkaz TworzRozkaz(string parametr, Centrala info)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FR_Poligon()
	{
		throw new System.NotImplementedException();
	}

}

