//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class R_DodajZasobWojskowy : Abstrakcyjny_Rozkaz
{
	public override void Raportuj(string rezultat)
	{
		throw new System.NotImplementedException();
	}

	public R_DodajZasobWojskowy()
	{
	}

}

